# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_decision.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='player_decision.proto',
  package='player_communication',
  syntax='proto3',
  serialized_options=b'\n3mech.mania.engine.server.communication.player.modelB\024PlayerDecisionProtos',
  serialized_pb=b'\n\x15player_decision.proto\x12\x14player_communication\"8\n\x0ePlayerDecision\x12\x12\n\nplayerUuid\x18\x01 \x01(\t\x12\x12\n\nplayerName\x18\x02 \x01(\tBK\n3mech.mania.engine.server.communication.player.modelB\x14PlayerDecisionProtosb\x06proto3'
)




_PLAYERDECISION = _descriptor.Descriptor(
  name='PlayerDecision',
  full_name='player_communication.PlayerDecision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerUuid', full_name='player_communication.PlayerDecision.playerUuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerName', full_name='player_communication.PlayerDecision.playerName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['PlayerDecision'] = _PLAYERDECISION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerDecision = _reflection.GeneratedProtocolMessageType('PlayerDecision', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERDECISION,
  '__module__' : 'player_decision_pb2'
  # @@protoc_insertion_point(class_scope:player_communication.PlayerDecision)
  })
_sym_db.RegisterMessage(PlayerDecision)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
