# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_turn.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='player_turn.proto',
  package='player_communication',
  syntax='proto3',
  serialized_options=b'\n3mech.mania.engine.server.communication.player.modelB\020PlayerTurnProtos',
  serialized_pb=b'\n\x11player_turn.proto\x12\x14player_communication\"4\n\nPlayerTurn\x12\x12\n\nplayerUuid\x18\x01 \x01(\t\x12\x12\n\nplayerName\x18\x02 \x01(\tBG\n3mech.mania.engine.server.communication.player.modelB\x10PlayerTurnProtosb\x06proto3'
)




_PLAYERTURN = _descriptor.Descriptor(
  name='PlayerTurn',
  full_name='player_communication.PlayerTurn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerUuid', full_name='player_communication.PlayerTurn.playerUuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerName', full_name='player_communication.PlayerTurn.playerName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['PlayerTurn'] = _PLAYERTURN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerTurn = _reflection.GeneratedProtocolMessageType('PlayerTurn', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERTURN,
  '__module__' : 'player_turn_pb2'
  # @@protoc_insertion_point(class_scope:player_communication.PlayerTurn)
  })
_sym_db.RegisterMessage(PlayerTurn)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
