# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import game_pb2 as game__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='player.proto',
  package='player_communication',
  syntax='proto3',
  serialized_options=_b('\n\036mech.mania.engine.domain.modelB\014PlayerProtos\252\002\016MM26.IO.Models'),
  serialized_pb=_b('\n\x0cplayer.proto\x12\x14player_communication\x1a\ngame.proto\"F\n\nPlayerTurn\x12#\n\ngame_state\x18\x01 \x01(\x0b\x32\x0f.game.GameState\x12\x13\n\x0bplayer_name\x18\x02 \x01(\tB?\n\x1emech.mania.engine.domain.modelB\x0cPlayerProtos\xaa\x02\x0eMM26.IO.Modelsb\x06proto3')
  ,
  dependencies=[game__pb2.DESCRIPTOR,])




_PLAYERTURN = _descriptor.Descriptor(
  name='PlayerTurn',
  full_name='player_communication.PlayerTurn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_state', full_name='player_communication.PlayerTurn.game_state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_name', full_name='player_communication.PlayerTurn.player_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=120,
)

_PLAYERTURN.fields_by_name['game_state'].message_type = game__pb2._GAMESTATE
DESCRIPTOR.message_types_by_name['PlayerTurn'] = _PLAYERTURN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerTurn = _reflection.GeneratedProtocolMessageType('PlayerTurn', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERTURN,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player_communication.PlayerTurn)
  })
_sym_db.RegisterMessage(PlayerTurn)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
