# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visualizer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import game_pb2 as game__pb2
from . import character_pb2 as character__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='visualizer.proto',
  package='player_communication',
  syntax='proto3',
  serialized_options=_b('\n\036mech.mania.engine.domain.modelB\020VisualizerProtos\252\002\016MM26.IO.Models'),
  serialized_pb=_b('\n\x10visualizer.proto\x12\x14player_communication\x1a\ngame.proto\x1a\x0f\x63haracter.proto\"3\n\x11VisualizerInitial\x12\x1e\n\x05state\x18\x01 \x01(\x0b\x32\x0f.game.GameState\"b\n\x0eVisualizerTurn\x12\x1e\n\x05state\x18\x01 \x01(\x0b\x32\x0f.game.GameState\x12\x30\n\x06\x63hange\x18\x02 \x01(\x0b\x32 .player_communication.GameChange\"\x89\x02\n\nGameChange\x12\x18\n\x10new_player_names\x18\x01 \x03(\t\x12Q\n\x11\x63haracter_changes\x18\x02 \x03(\x0b\x32\x36.player_communication.GameChange.CharacterChangesEntry\x12.\n\x11tile_item_changes\x18\x03 \x03(\x0b\x32\x13.character.Position\x1a^\n\x15\x43haracterChangesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.player_communication.CharacterChange:\x02\x38\x01\"\xac\x02\n\x0f\x43haracterChange\x12\x0c\n\x04\x64ied\x18\x01 \x01(\x08\x12\x11\n\trespawned\x18\x02 \x01(\x08\x12.\n\x08\x64\x65\x63ision\x18\x03 \x01(\x0b\x32\x1c.character.CharacterDecision\x12!\n\x04path\x18\x04 \x03(\x0b\x32\x13.character.Position\x12\x13\n\x0bhat_changed\x18\x05 \x01(\x08\x12\x17\n\x0f\x63lothes_changed\x18\x06 \x01(\x08\x12\x15\n\rshoes_changed\x18\x07 \x01(\x08\x12\x16\n\x0eweapon_changed\x18\x08 \x01(\x08\x12\x19\n\x11\x61\x63\x63\x65ssory_changed\x18\t \x01(\x08\x12-\n\x10\x61ttack_locations\x18\n \x03(\x0b\x32\x13.character.PositionBC\n\x1emech.mania.engine.domain.modelB\x10VisualizerProtos\xaa\x02\x0eMM26.IO.Modelsb\x06proto3')
  ,
  dependencies=[game__pb2.DESCRIPTOR,character__pb2.DESCRIPTOR,])




_VISUALIZERINITIAL = _descriptor.Descriptor(
  name='VisualizerInitial',
  full_name='player_communication.VisualizerInitial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='player_communication.VisualizerInitial.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=122,
)


_VISUALIZERTURN = _descriptor.Descriptor(
  name='VisualizerTurn',
  full_name='player_communication.VisualizerTurn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='player_communication.VisualizerTurn.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='change', full_name='player_communication.VisualizerTurn.change', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=222,
)


_GAMECHANGE_CHARACTERCHANGESENTRY = _descriptor.Descriptor(
  name='CharacterChangesEntry',
  full_name='player_communication.GameChange.CharacterChangesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='player_communication.GameChange.CharacterChangesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='player_communication.GameChange.CharacterChangesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=490,
)

_GAMECHANGE = _descriptor.Descriptor(
  name='GameChange',
  full_name='player_communication.GameChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='new_player_names', full_name='player_communication.GameChange.new_player_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='character_changes', full_name='player_communication.GameChange.character_changes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tile_item_changes', full_name='player_communication.GameChange.tile_item_changes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GAMECHANGE_CHARACTERCHANGESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=490,
)


_CHARACTERCHANGE = _descriptor.Descriptor(
  name='CharacterChange',
  full_name='player_communication.CharacterChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='died', full_name='player_communication.CharacterChange.died', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='respawned', full_name='player_communication.CharacterChange.respawned', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decision', full_name='player_communication.CharacterChange.decision', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='player_communication.CharacterChange.path', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hat_changed', full_name='player_communication.CharacterChange.hat_changed', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clothes_changed', full_name='player_communication.CharacterChange.clothes_changed', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shoes_changed', full_name='player_communication.CharacterChange.shoes_changed', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weapon_changed', full_name='player_communication.CharacterChange.weapon_changed', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accessory_changed', full_name='player_communication.CharacterChange.accessory_changed', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attack_locations', full_name='player_communication.CharacterChange.attack_locations', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=793,
)

_VISUALIZERINITIAL.fields_by_name['state'].message_type = game__pb2._GAMESTATE
_VISUALIZERTURN.fields_by_name['state'].message_type = game__pb2._GAMESTATE
_VISUALIZERTURN.fields_by_name['change'].message_type = _GAMECHANGE
_GAMECHANGE_CHARACTERCHANGESENTRY.fields_by_name['value'].message_type = _CHARACTERCHANGE
_GAMECHANGE_CHARACTERCHANGESENTRY.containing_type = _GAMECHANGE
_GAMECHANGE.fields_by_name['character_changes'].message_type = _GAMECHANGE_CHARACTERCHANGESENTRY
_GAMECHANGE.fields_by_name['tile_item_changes'].message_type = character__pb2._POSITION
_CHARACTERCHANGE.fields_by_name['decision'].message_type = character__pb2._CHARACTERDECISION
_CHARACTERCHANGE.fields_by_name['path'].message_type = character__pb2._POSITION
_CHARACTERCHANGE.fields_by_name['attack_locations'].message_type = character__pb2._POSITION
DESCRIPTOR.message_types_by_name['VisualizerInitial'] = _VISUALIZERINITIAL
DESCRIPTOR.message_types_by_name['VisualizerTurn'] = _VISUALIZERTURN
DESCRIPTOR.message_types_by_name['GameChange'] = _GAMECHANGE
DESCRIPTOR.message_types_by_name['CharacterChange'] = _CHARACTERCHANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisualizerInitial = _reflection.GeneratedProtocolMessageType('VisualizerInitial', (_message.Message,), {
  'DESCRIPTOR' : _VISUALIZERINITIAL,
  '__module__' : 'visualizer_pb2'
  # @@protoc_insertion_point(class_scope:player_communication.VisualizerInitial)
  })
_sym_db.RegisterMessage(VisualizerInitial)

VisualizerTurn = _reflection.GeneratedProtocolMessageType('VisualizerTurn', (_message.Message,), {
  'DESCRIPTOR' : _VISUALIZERTURN,
  '__module__' : 'visualizer_pb2'
  # @@protoc_insertion_point(class_scope:player_communication.VisualizerTurn)
  })
_sym_db.RegisterMessage(VisualizerTurn)

GameChange = _reflection.GeneratedProtocolMessageType('GameChange', (_message.Message,), {

  'CharacterChangesEntry' : _reflection.GeneratedProtocolMessageType('CharacterChangesEntry', (_message.Message,), {
    'DESCRIPTOR' : _GAMECHANGE_CHARACTERCHANGESENTRY,
    '__module__' : 'visualizer_pb2'
    # @@protoc_insertion_point(class_scope:player_communication.GameChange.CharacterChangesEntry)
    })
  ,
  'DESCRIPTOR' : _GAMECHANGE,
  '__module__' : 'visualizer_pb2'
  # @@protoc_insertion_point(class_scope:player_communication.GameChange)
  })
_sym_db.RegisterMessage(GameChange)
_sym_db.RegisterMessage(GameChange.CharacterChangesEntry)

CharacterChange = _reflection.GeneratedProtocolMessageType('CharacterChange', (_message.Message,), {
  'DESCRIPTOR' : _CHARACTERCHANGE,
  '__module__' : 'visualizer_pb2'
  # @@protoc_insertion_point(class_scope:player_communication.CharacterChange)
  })
_sym_db.RegisterMessage(CharacterChange)


DESCRIPTOR._options = None
_GAMECHANGE_CHARACTERCHANGESENTRY._options = None
# @@protoc_insertion_point(module_scope)
