# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: board.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.item_pb2 as item__pb2
import protos.character_pb2 as character__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='board.proto',
  package='board',
  syntax='proto3',
  serialized_options=b'\n\034mech.mania.engine.game.boardB\013BoardProtos\252\002\016MM26.IO.Models',
  serialized_pb=b'\n\x0b\x62oard.proto\x12\x05\x62oard\x1a\nitem.proto\x1a\x0f\x63haracter.proto\"\xc0\x01\n\x05\x42oard\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\x05\x12\x19\n\x04grid\x18\x03 \x03(\x0b\x32\x0b.board.Tile\x12!\n\x07\x65nemies\x18\x04 \x03(\x0b\x32\x10.character.Enemy\x12\"\n\x07players\x18\x05 \x03(\x0b\x32\x11.character.Player\x12$\n\x07portals\x18\x06 \x03(\x0b\x32\x13.character.Position\x12\x10\n\x08\x62oard_id\x18\x07 \x01(\t\"\x90\x01\n\x04Tile\x12\'\n\ttile_type\x18\x01 \x01(\x0e\x32\x14.board.Tile.TileType\x12\x19\n\x05items\x18\x02 \x03(\x0b\x32\n.item.Item\"D\n\x08TileType\x12\x08\n\x04VOID\x10\x00\x12\t\n\x05\x42LANK\x10\x01\x12\x0e\n\nIMPASSIBLE\x10\x02\x12\x07\n\x03INN\x10\x03\x12\n\n\x06PORTAL\x10\x04\x42<\n\x1cmech.mania.engine.game.boardB\x0b\x42oardProtos\xaa\x02\x0eMM26.IO.Modelsb\x06proto3'
  ,
  dependencies=[item__pb2.DESCRIPTOR,character__pb2.DESCRIPTOR,])



_TILE_TILETYPE = _descriptor.EnumDescriptor(
  name='TileType',
  full_name='board.Tile.TileType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VOID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLANK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMPASSIBLE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PORTAL', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=323,
  serialized_end=391,
)
_sym_db.RegisterEnumDescriptor(_TILE_TILETYPE)


_BOARD = _descriptor.Descriptor(
  name='Board',
  full_name='board.Board',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='board.Board.rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='columns', full_name='board.Board.columns', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid', full_name='board.Board.grid', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enemies', full_name='board.Board.enemies', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='players', full_name='board.Board.players', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='portals', full_name='board.Board.portals', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='board_id', full_name='board.Board.board_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=244,
)


_TILE = _descriptor.Descriptor(
  name='Tile',
  full_name='board.Tile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tile_type', full_name='board.Tile.tile_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='board.Tile.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TILE_TILETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=391,
)

_BOARD.fields_by_name['grid'].message_type = _TILE
_BOARD.fields_by_name['enemies'].message_type = character__pb2._ENEMY
_BOARD.fields_by_name['players'].message_type = character__pb2._PLAYER
_BOARD.fields_by_name['portals'].message_type = character__pb2._POSITION
_TILE.fields_by_name['tile_type'].enum_type = _TILE_TILETYPE
_TILE.fields_by_name['items'].message_type = item__pb2._ITEM
_TILE_TILETYPE.containing_type = _TILE
DESCRIPTOR.message_types_by_name['Board'] = _BOARD
DESCRIPTOR.message_types_by_name['Tile'] = _TILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Board = _reflection.GeneratedProtocolMessageType('Board', (_message.Message,), {
  'DESCRIPTOR' : _BOARD,
  '__module__' : 'board_pb2'
  # @@protoc_insertion_point(class_scope:board.Board)
  })
_sym_db.RegisterMessage(Board)

Tile = _reflection.GeneratedProtocolMessageType('Tile', (_message.Message,), {
  'DESCRIPTOR' : _TILE,
  '__module__' : 'board_pb2'
  # @@protoc_insertion_point(class_scope:board.Tile)
  })
_sym_db.RegisterMessage(Tile)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
