# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: character.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.item_pb2 as item__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='character.proto',
  package='character',
  syntax='proto3',
  serialized_options=b'\n!mech.mania.engine.game.charactersB\017CharacterProtos\252\002\016MM26.IO.Models',
  serialized_pb=b'\n\x0f\x63haracter.proto\x12\tcharacter\x1a\nitem.proto\"\x93\x01\n\x05\x45nemy\x12\x16\n\x0e\x63urrent_health\x18\x01 \x01(\x01\x12\x12\n\nexperience\x18\x02 \x01(\x05\x12%\n\x08position\x18\x03 \x01(\x0b\x32\x13.character.Position\x12\x1c\n\x06weapon\x18\x04 \x01(\x0b\x32\x0c.item.Weapon\x12\x19\n\x05\x64rops\x18\x05 \x03(\x0b\x32\n.item.Item\"\xc2\x02\n\x06Player\x12\x16\n\x0e\x63urrent_health\x18\x01 \x01(\x01\x12\x12\n\nexperience\x18\x02 \x01(\x05\x12%\n\x08position\x18\x03 \x01(\x0b\x32\x13.character.Position\x12\x1c\n\x06weapon\x18\x04 \x01(\x0b\x32\x0c.item.Weapon\x12\x15\n\rinventorySize\x18\x05 \x01(\x05\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x16\n\x03hat\x18\x07 \x01(\x0b\x32\t.item.Hat\x12\x1e\n\x07\x63lothes\x18\x08 \x01(\x0b\x32\r.item.Clothes\x12\x1a\n\x05shoes\x18\t \x01(\x0b\x32\x0b.item.Shoes\x12\x1d\n\tinventory\x18\n \x03(\x0b\x32\n.item.Item\x12/\n\ractiveEffects\x18\x0b \x03(\x0b\x32\x18.item.TempStatusModifier\"1\n\x08Position\x12\x0f\n\x07\x62oardId\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x42\x45\n!mech.mania.engine.game.charactersB\x0f\x43haracterProtos\xaa\x02\x0eMM26.IO.Modelsb\x06proto3'
  ,
  dependencies=[item__pb2.DESCRIPTOR,])




_ENEMY = _descriptor.Descriptor(
  name='Enemy',
  full_name='character.Enemy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_health', full_name='character.Enemy.current_health', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='experience', full_name='character.Enemy.experience', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='character.Enemy.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weapon', full_name='character.Enemy.weapon', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='drops', full_name='character.Enemy.drops', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=190,
)


_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='character.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_health', full_name='character.Player.current_health', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='experience', full_name='character.Player.experience', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='character.Player.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weapon', full_name='character.Player.weapon', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inventorySize', full_name='character.Player.inventorySize', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='character.Player.name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hat', full_name='character.Player.hat', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clothes', full_name='character.Player.clothes', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shoes', full_name='character.Player.shoes', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inventory', full_name='character.Player.inventory', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activeEffects', full_name='character.Player.activeEffects', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=515,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='character.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boardId', full_name='character.Position.boardId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='character.Position.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='character.Position.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=566,
)

_ENEMY.fields_by_name['position'].message_type = _POSITION
_ENEMY.fields_by_name['weapon'].message_type = item__pb2._WEAPON
_ENEMY.fields_by_name['drops'].message_type = item__pb2._ITEM
_PLAYER.fields_by_name['position'].message_type = _POSITION
_PLAYER.fields_by_name['weapon'].message_type = item__pb2._WEAPON
_PLAYER.fields_by_name['hat'].message_type = item__pb2._HAT
_PLAYER.fields_by_name['clothes'].message_type = item__pb2._CLOTHES
_PLAYER.fields_by_name['shoes'].message_type = item__pb2._SHOES
_PLAYER.fields_by_name['inventory'].message_type = item__pb2._ITEM
_PLAYER.fields_by_name['activeEffects'].message_type = item__pb2._TEMPSTATUSMODIFIER
DESCRIPTOR.message_types_by_name['Enemy'] = _ENEMY
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Enemy = _reflection.GeneratedProtocolMessageType('Enemy', (_message.Message,), {
  'DESCRIPTOR' : _ENEMY,
  '__module__' : 'character_pb2'
  # @@protoc_insertion_point(class_scope:character.Enemy)
  })
_sym_db.RegisterMessage(Enemy)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), {
  'DESCRIPTOR' : _PLAYER,
  '__module__' : 'character_pb2'
  # @@protoc_insertion_point(class_scope:character.Player)
  })
_sym_db.RegisterMessage(Player)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'character_pb2'
  # @@protoc_insertion_point(class_scope:character.Position)
  })
_sym_db.RegisterMessage(Position)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
