# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.board_pb2 as board__pb2
import protos.character_pb2 as character__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='game_state.proto',
  package='game_state',
  syntax='proto3',
  serialized_options=b'\n\034mech.mania.engine.game.modelB\017GameStateProtos\252\002\016MM26.IO.Models',
  serialized_pb=b'\n\x10game_state.proto\x12\ngame_state\x1a\x0b\x62oard.proto\x1a\x0f\x63haracter.proto\"\xd1\x01\n\tGameState\x12\x10\n\x08state_id\x18\x01 \x01(\x03\x12\x1e\n\x08pvpBoard\x18\x02 \x01(\x0b\x32\x0c.board.Board\x12I\n\x12playerIdToBoardMap\x18\x03 \x03(\x0b\x32-.game_state.GameState.PlayerIdToBoardMapEntry\x1aG\n\x17PlayerIdToBoardMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.board.Board:\x02\x38\x01\"\x1f\n\nGameChange\x12\x11\n\tchange_id\x18\x01 \x01(\x03\x42@\n\x1cmech.mania.engine.game.modelB\x0fGameStateProtos\xaa\x02\x0eMM26.IO.Modelsb\x06proto3'
  ,
  dependencies=[board__pb2.DESCRIPTOR,character__pb2.DESCRIPTOR,])




_GAMESTATE_PLAYERIDTOBOARDMAPENTRY = _descriptor.Descriptor(
  name='PlayerIdToBoardMapEntry',
  full_name='game_state.GameState.PlayerIdToBoardMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='game_state.GameState.PlayerIdToBoardMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='game_state.GameState.PlayerIdToBoardMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=272,
)

_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='game_state.GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state_id', full_name='game_state.GameState.state_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pvpBoard', full_name='game_state.GameState.pvpBoard', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerIdToBoardMap', full_name='game_state.GameState.playerIdToBoardMap', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GAMESTATE_PLAYERIDTOBOARDMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=272,
)


_GAMECHANGE = _descriptor.Descriptor(
  name='GameChange',
  full_name='game_state.GameChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='change_id', full_name='game_state.GameChange.change_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=305,
)

_GAMESTATE_PLAYERIDTOBOARDMAPENTRY.fields_by_name['value'].message_type = board__pb2._BOARD
_GAMESTATE_PLAYERIDTOBOARDMAPENTRY.containing_type = _GAMESTATE
_GAMESTATE.fields_by_name['pvpBoard'].message_type = board__pb2._BOARD
_GAMESTATE.fields_by_name['playerIdToBoardMap'].message_type = _GAMESTATE_PLAYERIDTOBOARDMAPENTRY
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE
DESCRIPTOR.message_types_by_name['GameChange'] = _GAMECHANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), {

  'PlayerIdToBoardMapEntry' : _reflection.GeneratedProtocolMessageType('PlayerIdToBoardMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _GAMESTATE_PLAYERIDTOBOARDMAPENTRY,
    '__module__' : 'game_state_pb2'
    # @@protoc_insertion_point(class_scope:game_state.GameState.PlayerIdToBoardMapEntry)
    })
  ,
  'DESCRIPTOR' : _GAMESTATE,
  '__module__' : 'game_state_pb2'
  # @@protoc_insertion_point(class_scope:game_state.GameState)
  })
_sym_db.RegisterMessage(GameState)
_sym_db.RegisterMessage(GameState.PlayerIdToBoardMapEntry)

GameChange = _reflection.GeneratedProtocolMessageType('GameChange', (_message.Message,), {
  'DESCRIPTOR' : _GAMECHANGE,
  '__module__' : 'game_state_pb2'
  # @@protoc_insertion_point(class_scope:game_state.GameChange)
  })
_sym_db.RegisterMessage(GameChange)


DESCRIPTOR._options = None
_GAMESTATE_PLAYERIDTOBOARDMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
