# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='item.proto',
  package='item',
  syntax='proto3',
  serialized_options=b'\n\034mech.mania.engine.game.itemsB\nItemProtos\252\002\016MM26.IO.Models',
  serialized_pb=b'\n\nitem.proto\x12\x04item\"\xe8\x01\n\x04Item\x12\x11\n\tmax_stack\x18\x01 \x01(\x05\x12#\n\x05stats\x18\x02 \x01(\x0b\x32\x14.item.StatusModifier\x12 \n\x07\x63lothes\x18\x03 \x01(\x0b\x32\r.item.ClothesH\x00\x12\x18\n\x03hat\x18\x04 \x01(\x0b\x32\t.item.HatH\x00\x12\x1c\n\x05shoes\x18\x05 \x01(\x0b\x32\x0b.item.ShoesH\x00\x12\x1e\n\x06weapon\x18\x06 \x01(\x0b\x32\x0c.item.WeaponH\x00\x12&\n\nconsumable\x18\x07 \x01(\x0b\x32\x10.item.ConsumableH\x00\x42\x06\n\x04item\".\n\x07\x43lothes\x12#\n\x05stats\x18\x01 \x01(\x0b\x32\x14.item.StatusModifier\"j\n\x03Hat\x12#\n\x05stats\x18\x01 \x01(\x0b\x32\x14.item.StatusModifier\x12\'\n\nhat_effect\x18\x02 \x01(\x0e\x32\x13.item.Hat.HatEffect\"\x15\n\tHatEffect\x12\x08\n\x04TEST\x10\x00\",\n\x05Shoes\x12#\n\x05stats\x18\x01 \x01(\x0b\x32\x14.item.StatusModifier\"\x84\x01\n\x06Weapon\x12#\n\x05stats\x18\x01 \x01(\x0b\x32\x14.item.StatusModifier\x12\r\n\x05range\x18\x02 \x01(\x05\x12\x15\n\rsplash_radius\x18\x03 \x01(\x05\x12/\n\ron_hit_effect\x18\x04 \x01(\x0b\x32\x18.item.TempStatusModifier\"5\n\nConsumable\x12\'\n\x05stats\x18\x01 \x01(\x0b\x32\x18.item.TempStatusModifier\"\xd4\x01\n\x0eStatusModifier\x12\x14\n\x0cspeed_change\x18\x01 \x01(\x05\x12\x15\n\rhealth_change\x18\x02 \x01(\x05\x12\x19\n\x11\x65xperience_change\x18\x03 \x01(\x05\x12\x1b\n\x13magic_damage_change\x18\x04 \x01(\x05\x12\x1e\n\x16physical_damage_change\x18\x05 \x01(\x05\x12\x1c\n\x14magic_defense_change\x18\x06 \x01(\x05\x12\x1f\n\x17physical_defense_change\x18\x07 \x01(\x05\"d\n\x12TempStatusModifier\x12#\n\x05stats\x18\x01 \x01(\x0b\x32\x14.item.StatusModifier\x12\x17\n\x0f\x64\x61mage_per_turn\x18\x02 \x01(\x01\x12\x10\n\x08\x64uration\x18\x03 \x01(\x05\x42;\n\x1cmech.mania.engine.game.itemsB\nItemProtos\xaa\x02\x0eMM26.IO.Modelsb\x06proto3'
)



_HAT_HATEFFECT = _descriptor.EnumDescriptor(
  name='HatEffect',
  full_name='item.Hat.HatEffect',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEST', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=388,
  serialized_end=409,
)
_sym_db.RegisterEnumDescriptor(_HAT_HATEFFECT)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='item.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_stack', full_name='item.Item.max_stack', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stats', full_name='item.Item.stats', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clothes', full_name='item.Item.clothes', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hat', full_name='item.Item.hat', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shoes', full_name='item.Item.shoes', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weapon', full_name='item.Item.weapon', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consumable', full_name='item.Item.consumable', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='item', full_name='item.Item.item',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=21,
  serialized_end=253,
)


_CLOTHES = _descriptor.Descriptor(
  name='Clothes',
  full_name='item.Clothes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='item.Clothes.stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=301,
)


_HAT = _descriptor.Descriptor(
  name='Hat',
  full_name='item.Hat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='item.Hat.stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hat_effect', full_name='item.Hat.hat_effect', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HAT_HATEFFECT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=409,
)


_SHOES = _descriptor.Descriptor(
  name='Shoes',
  full_name='item.Shoes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='item.Shoes.stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=455,
)


_WEAPON = _descriptor.Descriptor(
  name='Weapon',
  full_name='item.Weapon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='item.Weapon.stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range', full_name='item.Weapon.range', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='splash_radius', full_name='item.Weapon.splash_radius', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='on_hit_effect', full_name='item.Weapon.on_hit_effect', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=590,
)


_CONSUMABLE = _descriptor.Descriptor(
  name='Consumable',
  full_name='item.Consumable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='item.Consumable.stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=645,
)


_STATUSMODIFIER = _descriptor.Descriptor(
  name='StatusModifier',
  full_name='item.StatusModifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed_change', full_name='item.StatusModifier.speed_change', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='health_change', full_name='item.StatusModifier.health_change', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='experience_change', full_name='item.StatusModifier.experience_change', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='magic_damage_change', full_name='item.StatusModifier.magic_damage_change', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='physical_damage_change', full_name='item.StatusModifier.physical_damage_change', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='magic_defense_change', full_name='item.StatusModifier.magic_defense_change', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='physical_defense_change', full_name='item.StatusModifier.physical_defense_change', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=648,
  serialized_end=860,
)


_TEMPSTATUSMODIFIER = _descriptor.Descriptor(
  name='TempStatusModifier',
  full_name='item.TempStatusModifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='item.TempStatusModifier.stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='damage_per_turn', full_name='item.TempStatusModifier.damage_per_turn', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='item.TempStatusModifier.duration', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=862,
  serialized_end=962,
)

_ITEM.fields_by_name['stats'].message_type = _STATUSMODIFIER
_ITEM.fields_by_name['clothes'].message_type = _CLOTHES
_ITEM.fields_by_name['hat'].message_type = _HAT
_ITEM.fields_by_name['shoes'].message_type = _SHOES
_ITEM.fields_by_name['weapon'].message_type = _WEAPON
_ITEM.fields_by_name['consumable'].message_type = _CONSUMABLE
_ITEM.oneofs_by_name['item'].fields.append(
  _ITEM.fields_by_name['clothes'])
_ITEM.fields_by_name['clothes'].containing_oneof = _ITEM.oneofs_by_name['item']
_ITEM.oneofs_by_name['item'].fields.append(
  _ITEM.fields_by_name['hat'])
_ITEM.fields_by_name['hat'].containing_oneof = _ITEM.oneofs_by_name['item']
_ITEM.oneofs_by_name['item'].fields.append(
  _ITEM.fields_by_name['shoes'])
_ITEM.fields_by_name['shoes'].containing_oneof = _ITEM.oneofs_by_name['item']
_ITEM.oneofs_by_name['item'].fields.append(
  _ITEM.fields_by_name['weapon'])
_ITEM.fields_by_name['weapon'].containing_oneof = _ITEM.oneofs_by_name['item']
_ITEM.oneofs_by_name['item'].fields.append(
  _ITEM.fields_by_name['consumable'])
_ITEM.fields_by_name['consumable'].containing_oneof = _ITEM.oneofs_by_name['item']
_CLOTHES.fields_by_name['stats'].message_type = _STATUSMODIFIER
_HAT.fields_by_name['stats'].message_type = _STATUSMODIFIER
_HAT.fields_by_name['hat_effect'].enum_type = _HAT_HATEFFECT
_HAT_HATEFFECT.containing_type = _HAT
_SHOES.fields_by_name['stats'].message_type = _STATUSMODIFIER
_WEAPON.fields_by_name['stats'].message_type = _STATUSMODIFIER
_WEAPON.fields_by_name['on_hit_effect'].message_type = _TEMPSTATUSMODIFIER
_CONSUMABLE.fields_by_name['stats'].message_type = _TEMPSTATUSMODIFIER
_TEMPSTATUSMODIFIER.fields_by_name['stats'].message_type = _STATUSMODIFIER
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['Clothes'] = _CLOTHES
DESCRIPTOR.message_types_by_name['Hat'] = _HAT
DESCRIPTOR.message_types_by_name['Shoes'] = _SHOES
DESCRIPTOR.message_types_by_name['Weapon'] = _WEAPON
DESCRIPTOR.message_types_by_name['Consumable'] = _CONSUMABLE
DESCRIPTOR.message_types_by_name['StatusModifier'] = _STATUSMODIFIER
DESCRIPTOR.message_types_by_name['TempStatusModifier'] = _TEMPSTATUSMODIFIER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:item.Item)
  })
_sym_db.RegisterMessage(Item)

Clothes = _reflection.GeneratedProtocolMessageType('Clothes', (_message.Message,), {
  'DESCRIPTOR' : _CLOTHES,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:item.Clothes)
  })
_sym_db.RegisterMessage(Clothes)

Hat = _reflection.GeneratedProtocolMessageType('Hat', (_message.Message,), {
  'DESCRIPTOR' : _HAT,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:item.Hat)
  })
_sym_db.RegisterMessage(Hat)

Shoes = _reflection.GeneratedProtocolMessageType('Shoes', (_message.Message,), {
  'DESCRIPTOR' : _SHOES,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:item.Shoes)
  })
_sym_db.RegisterMessage(Shoes)

Weapon = _reflection.GeneratedProtocolMessageType('Weapon', (_message.Message,), {
  'DESCRIPTOR' : _WEAPON,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:item.Weapon)
  })
_sym_db.RegisterMessage(Weapon)

Consumable = _reflection.GeneratedProtocolMessageType('Consumable', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMABLE,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:item.Consumable)
  })
_sym_db.RegisterMessage(Consumable)

StatusModifier = _reflection.GeneratedProtocolMessageType('StatusModifier', (_message.Message,), {
  'DESCRIPTOR' : _STATUSMODIFIER,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:item.StatusModifier)
  })
_sym_db.RegisterMessage(StatusModifier)

TempStatusModifier = _reflection.GeneratedProtocolMessageType('TempStatusModifier', (_message.Message,), {
  'DESCRIPTOR' : _TEMPSTATUSMODIFIER,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:item.TempStatusModifier)
  })
_sym_db.RegisterMessage(TempStatusModifier)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
