# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_protos.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.game_state_pb2 as game__state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='player_protos.proto',
  package='player_communication',
  syntax='proto3',
  serialized_options=b'\n3mech.mania.engine.server.communication.player.modelB\014PlayerProtos',
  serialized_pb=b'\n\x13player_protos.proto\x12\x14player_communication\x1a\x10game_state.proto\"M\n\x0ePlayerDecision\x12\x13\n\x0bplayer_uuid\x18\x01 \x01(\t\x12\x13\n\x0bplayer_name\x18\x02 \x01(\t\x12\x11\n\tincrement\x18\x03 \x01(\x05\"\x89\x01\n\nPlayerTurn\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\x12\x11\n\tincrement\x18\x02 \x01(\x05\x12)\n\ngame_state\x18\x04 \x01(\x0b\x32\x15.game_state.GameState\x12\x0f\n\x05test1\x18\x05 \x01(\tH\x00\x12\x0f\n\x05test2\x18\x06 \x01(\x05H\x00\x42\x06\n\x04testBC\n3mech.mania.engine.server.communication.player.modelB\x0cPlayerProtosb\x06proto3'
  ,
  dependencies=[game__state__pb2.DESCRIPTOR,])




_PLAYERDECISION = _descriptor.Descriptor(
  name='PlayerDecision',
  full_name='player_communication.PlayerDecision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_uuid', full_name='player_communication.PlayerDecision.player_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_name', full_name='player_communication.PlayerDecision.player_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='increment', full_name='player_communication.PlayerDecision.increment', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=140,
)


_PLAYERTURN = _descriptor.Descriptor(
  name='PlayerTurn',
  full_name='player_communication.PlayerTurn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_name', full_name='player_communication.PlayerTurn.player_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='increment', full_name='player_communication.PlayerTurn.increment', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_state', full_name='player_communication.PlayerTurn.game_state', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test1', full_name='player_communication.PlayerTurn.test1', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test2', full_name='player_communication.PlayerTurn.test2', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='test', full_name='player_communication.PlayerTurn.test',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=143,
  serialized_end=280,
)

_PLAYERTURN.fields_by_name['game_state'].message_type = game__state__pb2._GAMESTATE
_PLAYERTURN.oneofs_by_name['test'].fields.append(
  _PLAYERTURN.fields_by_name['test1'])
_PLAYERTURN.fields_by_name['test1'].containing_oneof = _PLAYERTURN.oneofs_by_name['test']
_PLAYERTURN.oneofs_by_name['test'].fields.append(
  _PLAYERTURN.fields_by_name['test2'])
_PLAYERTURN.fields_by_name['test2'].containing_oneof = _PLAYERTURN.oneofs_by_name['test']
DESCRIPTOR.message_types_by_name['PlayerDecision'] = _PLAYERDECISION
DESCRIPTOR.message_types_by_name['PlayerTurn'] = _PLAYERTURN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerDecision = _reflection.GeneratedProtocolMessageType('PlayerDecision', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERDECISION,
  '__module__' : 'player_protos_pb2'
  # @@protoc_insertion_point(class_scope:player_communication.PlayerDecision)
  })
_sym_db.RegisterMessage(PlayerDecision)

PlayerTurn = _reflection.GeneratedProtocolMessageType('PlayerTurn', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERTURN,
  '__module__' : 'player_protos_pb2'
  # @@protoc_insertion_point(class_scope:player_communication.PlayerTurn)
  })
_sym_db.RegisterMessage(PlayerTurn)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
